# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_lidar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lidar.setGeometry(QtCore.QRect(140, 110, 250, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_lidar.setFont(font)
        self.pushButton_lidar.setObjectName("pushButton_lidar")
        self.pushButton_camera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_camera.setGeometry(QtCore.QRect(470, 110, 250, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_camera.setFont(font)
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.pushButton_roscore = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_roscore.setGeometry(QtCore.QRect(40, 30, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_roscore.setFont(font)
        self.pushButton_roscore.setObjectName("pushButton_roscore")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(40, 360, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_point_color = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_point_color.setGeometry(QtCore.QRect(40, 200, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_point_color.setFont(font)
        self.pushButton_point_color.setObjectName("pushButton_point_color")
        self.pushButton_rosbag = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rosbag.setGeometry(QtCore.QRect(140, 280, 250, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_rosbag.setFont(font)
        self.pushButton_rosbag.setObjectName("pushButton_rosbag")
        self.pushButton_slam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_slam.setGeometry(QtCore.QRect(330, 200, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_slam.setFont(font)
        self.pushButton_slam.setObjectName("pushButton_slam")
        self.pushButton_point_txt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_point_txt.setGeometry(QtCore.QRect(470, 280, 250, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_point_txt.setFont(font)
        self.pushButton_point_txt.setObjectName("pushButton_point_txt")
        self.pushButton_colored_point_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_colored_point_register.setGeometry(QtCore.QRect(620, 200, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_colored_point_register.setFont(font)
        self.pushButton_colored_point_register.setObjectName("pushButton_colored_point_register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_roscore.clicked.connect(MainWindow.func_roscore)
        self.pushButton_lidar.clicked.connect(MainWindow.func_lidar)
        self.pushButton_camera.clicked.connect(MainWindow.func_camera)
        self.pushButton_close.clicked.connect(MainWindow.func_close)
        self.pushButton_point_color.clicked.connect(MainWindow.func_point_color)
        self.pushButton_slam.clicked.connect(MainWindow.func_slam)
        self.pushButton_colored_point_register.clicked.connect(MainWindow.func_colored_point_register)
        self.pushButton_rosbag.clicked.connect(MainWindow.func_rosbag)
        self.pushButton_point_txt.clicked.connect(MainWindow.func_point_txt)
        # self.pushButton_rgbd.clicked.connect(MainWindow.func_rgbd)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowTitle(_translate("MainWindow", "同济测图系统"))
        MainWindow.setWindowIcon(QtGui.QIcon("/home/tongji-survey/pyqt_xzr/iconfinder_robot_2120162.ico"))

        self.pushButton_lidar.setText(_translate("MainWindow", "开启激光"))
        self.pushButton_camera.setText(_translate("MainWindow", "开启相机"))
        self.pushButton_roscore.setText(_translate("MainWindow", "系统准备"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭"))
        self.pushButton_point_color.setText(_translate("MainWindow", "相机激光配色"))
        self.pushButton_rosbag.setText(_translate("MainWindow", "所有数据存储"))
        self.pushButton_slam.setText(_translate("MainWindow", "轨迹计算"))
        self.pushButton_point_txt.setText(_translate("MainWindow", "彩色点云存储"))
        self.pushButton_colored_point_register.setText(_translate("MainWindow", "彩色点云配准"))
